### ISSUE TITLE
Potential fail regarding localization

### ISSUE THREAD

**Issue by dovisutu** [cScotPlay/BasicNetherOres#10]
Currently, the method used to register OreDictionary during initialization doesn't allow some localization:
https://github.com/cScotPlay/BasicNetherOres/blob/e3c139ebdd76741aee04da98b1293c029da89f16/src/main/java/cscot/basicnetherores/registries/OreDictionaryRegistry.java#L36
Where the `substring` operation on `LocalizedString` requires the **localized** text to be at least 6 charactors long. And if you want to keep the OreDictionary registered the same, you have to also keep the leading text exactly as what is in the English text, a.k.a:
```java properties
tile.block_copper.name=copper ***** # where *s are the only charactor that are able to change
```
Which is not only unfriendly to the localizers, but sometimes even **impossible** for some languages like Chinese.
Also, since the key (`tile.block_copper.name`) is quite common, we may end up has a collision of keys which let unrelated addition of a resource pack containing other mods' .lang break the game, which only deepens the mystery for gamers.

**Comment by cScotPlay** [comment]
Thanks for bringing this to my attention. I'll take a look at it and see what we can possibly do to make it more localization friendly.

**Comment by cScotPlay** [comment]
Updated the Ore Dictionary Registry may not be pretty but should work.  See version 1.12.2-1.0.5
