### ISSUE TITLE
Biomes o plenty compatibility

### ISSUE THREAD

**Issue by disastercube** [cScotPlay/BasicNetherOres#13]
Ores do not spawn in nether bioems of Bioems o Plenty. This potentially isn't a bad thing. Vanilla nether gets filled with ores which might make the game a lot easier but with biomes o plenty that adds new nether biomes, you can make it so it seems like the only biomes that ores spawn in is the basic one and that would coming across the empty vanilla biome instead of content lacking, one of the best since it would be the only one that would provide resources. 

Suggestion :
If this bug gets fixed and ores start to spawn in every biome, please make it so you can config in which biome ores spawn and maybe even what ores.

**Comment by cScotPlay** [comment]
Thanks for bringing this to my attention.  I've updated the biome checker to account for all biomes that designate "Nether" as one of their categories.  If the mod doesn't assign this to their biomes then the ores will not spawn in the biome.  BoP assigns its biomes with categories and now works.  At this point in time, I am going to refrain from adding the config to select specific biomes and then break down which ores can spawn per biome.  The mod already breaks the ores into elevation zones to create a bit of variety to the spawning mechanics.  We will revisit this when 1.16 drops to see the feasibility and playability of it.  Thanks again for reporting these issues.

Please refer to the following files for updates:
1.15.2 - [https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores/files/2966497](url)
1.14.4 - [https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores/files/2966495](url)
