### ISSUE TITLE
Osmium (Mekanism) support

### ISSUE THREAD

**Issue by Caltinor** [cScotPlay/BasicNetherOres#16]
If it is within the scope of modded ores support, could you please add Mekanism Osmium as an option?  Mekanism's v10 for 1.16 now takes advantage of lead and uranium ores and this addition would round out your mod's offerings to this mod as well.

**Comment by cScotPlay** [comment]
Working on getting it added.  Should have a release of it ready soon.

**Comment by Caltinor** [comment]
Awesome!  I saw the commits where you started.  I was no doubt excited.  Thank you.

**Comment by cScotPlay** [comment]
Enhancement added in version 1.16.1-5.1.0
