### ISSUE TITLE
[1.16.1-Suggestion] Change the mining sounds of nether ores to the new 1.16 Quartz Mining Sound.

### ISSUE THREAD

**Issue by Gbergz** [cScotPlay/BasicNetherOres#18]
Just to get the feeling of the 1.16 nether update.
Just a small suggestion, I hope you'll do it :)

**-** Gbergz

**Comment by cScotPlay** [comment]
It is on the list and actually added for the next release.

**Comment by cScotPlay** [comment]
Enhancement added in version 1.16.1 - 5.1.0.
