### ISSUE TITLE
Exit Code 0 Error

### ISSUE THREAD

**Issue by DatrixTHLK** [cScotPlay/BasicNetherOres#19]
Hi there,

When using basic nether ores the error I mentioned in the title shows up.  Just crashes my game to desktop.
Minecraft: 1.16.2
Forge: 33.0.37
Basic Nether Ores: 5.1.0

FML Log: https://gist.github.com/DatrixTHLK/f2a49ac63d178316b811478c6118ea77

**Comment by Gbergz** [comment]
Latest Release for 1.16.2 is for Fabric if you didn’t know. But yes it’s giving me the same error on Fabric aswell.

**Comment by cScotPlay** [comment]
The most recent version for 1.16.2 is for Fabric but the Forge one should be out soon.  Give me a bit and let me see if I can get the error fixed.  Thanks for letting me know.

**Comment by DatrixTHLK** [comment]
Well the version I was using was the latest for forge.

**Comment by cScotPlay** [comment]
No problem.  I am working on getting the Forge version updated to 1.16.2.  I don't think the current Forge version "1.16.1-5.1.0 - Forge" will run in 1.16.2.   As for the Fabric version, just uploaded an update that should fix the problem that @Gbergz was having.  Thanks again and please know that we are trying to get the Forge version updated.
