### ISSUE TITLE
Smelting Recipes Behaving Weirdly

### ISSUE THREAD

**Issue by Rohzek** [cScotPlay/BasicNetherOres#2]
#### Versions:
* Basic Nether Ores: 2.0.0 (Beta)
* Forge: 25.0.219

#### Observed Behavior: 
The Modded/Extra ores smelting awkwardly. Aluminum, Lead, and Nickel won't smelt at all. Copper smelts into Aluminum ingots. Tin smelts correctly, as do all of the vanilla ores. Checked in both Vanilla furnace, and 'Iron Furnaces' furnaces.

#### Expected Behavior: 
Ores to smelt to their correct ingots.

#### Steps to Reproduce: 
Smelt the extra ores.

**Comment by cScotPlay** [comment]
Sorry just getting around to checking the issues here on GitHub.  This was an oversight that I made initially.  Try updating to one of the newer versions for the fix.  Thanks.
