### ISSUE TITLE
Basic Nether Ores (BNO) spawning in the overworld

### ISSUE THREAD

**Issue by RoaringCris** [cScotPlay/BasicNetherOres#22]
I do have silver enabled to spawn in the nether, but not in the overworld...

list of mods:
![2020-09-20](https://user-images.githubusercontent.com/71613411/93724531-c215e800-fb5c-11ea-9579-95fdec556e04.png)

proof:
![2020-09-20_16 14 06](https://user-images.githubusercontent.com/71613411/93724492-6186ab00-fb5c-11ea-8bf4-402e43f9f9a2.png)
![2020-09-20_16 14 14](https://user-images.githubusercontent.com/71613411/93724493-621f4180-fb5c-11ea-8de9-b29e14fece0f.png)

**Comment by cScotPlay** [comment]
Working to replicate this.  Are you able to provide the seed and coordinates for where you found this?

**Comment by NaomiKuroi** [comment]
I just had the same thing happen myself today.
Modlist:
![modlist](https://user-images.githubusercontent.com/47642944/113907678-8229f180-978a-11eb-9a80-9a11d2e9101f.png)

Seed: 7683363644388113742

![2021-04-07_10 13 30](https://user-images.githubusercontent.com/47642944/113907904-c5846000-978a-11eb-95a2-6157d4f05903.png)

**Comment by Cinderheart** [comment]
I know what causes this. Do you have large ore deposits installed? That mod causes large veins of ores to rarely appear in the overworld, but the ores it chooses can include ores meant to be from other dimensions.
