### ISSUE TITLE
Ores not respecting harverstability level

### ISSUE THREAD

**Issue by Ushupiuck** [cScotPlay/BasicNetherOres#28]
Despite TOP showing that the ores need a pickaxe to break them, you can actually harvest any ore by just punching at it.

I mean... I know netherrack is fragile, but I don't think it's supposed to be THAT fragile. XD

**Comment by cScotPlay** [comment]
What version and modloader are you running into this problem with?  Fabric/Forge?

**Comment by Ushupiuck** [comment]
My bad for not replying in time..! (Coulda sworn I sent this reply already)
this affects MC 1.16.3/4, on forge. **high chances** it affects Fabric as well, as this issue came from a change made by mojang (matter of fact, all mods that added ores were affected by it, or at least so I found on the forge side)

**Comment by cScotPlay** [comment]
Thanks for clueing me in on this.  Simple fix.  The Fabric release is unaffected by this as I rewrote most of the block properties when it was ported.  Version 5.3.1 has the fix.

**Comment by Ushupiuck** [comment]
@cScotPlay, your latest release doesn't address the issue completely! I just went to testing, and ALL ores require at least an iron pick to mine, even those that shouldn't (Copper, tin, coal, lapis, etc). Hopefully this can be resolved?

**Comment by cScotPlay** [comment]
Actually, that is intended.  It was the intent for all nether ores to require an iron pickaxe.

**Comment by Ushupiuck** [comment]
I digress. In the original mod, it was possible to use a cobblestone pickaxe to harvest basic ingredients like the ones mentioned. Not to mention, having all ores require at least an iron pickaxe makes it nearly impossible to harvest resources if you're doing nether survival...
