### ISSUE TITLE
Crash to desktop while initializing game

### ISSUE THREAD

**Issue by DatrixTHLK** [cScotPlay/BasicNetherOres#3]
Hi cScotPlay,

I have a feeling that I need some form of "coremod" or api for this to work besides forge. Don't know if there is one since I didn't see one in the relations tab in curseforge.
Minecraft: 1.14.4
Forge (BETA): 28.0.65+
Basic Nether Ores: 3.2.0

Crash: https://gist.github.com/DatrixTHLK/538357553b3c3f87b61de2c8de6d6630

**Comment by ovingiv** [comment]
I'm also having the same issue except on a newer (beta) of forge 28.0.72

Crash: https://paste.ee/p/qHiIQ

**Comment by Gamertech** [comment]
Identical crash log on Forge .75

**Comment by Alex1331xela** [comment]
Same issue here. Crashes on startup on Forge v28.0.65+

[Crashlog on v28.0.81](https://github.com/cScotPlay/BasicNetherOres/files/3563628/crash-2019-09-01_11.05.55-client.txt)

**Comment by cScotPlay** [comment]
Thank you all for bringing this to my attention.  The issue stems from Forge updated a couple of the checks we were using to identify if recipes were to load.  It actually was a larger problem that the Forge team said would break a fair amount of things.  I've updated to the newest version of Forge and it currently runs well on 28.0.83.  I hope that this fixes the issues you are seeing.  I've also added a bit more flexibility to the generation of the ores in the nether.  Please let me know if your issues still exist after this update.

The newest file is located at https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores/files/2776655

**Comment by Gamertech** [comment]
Loads past that point now thanks, now there's another mod in my list that crashes with new Forge... :(

Thanks for the bonus disable generation of ores though. That's a big help.

**Comment by DatrixTHLK** [comment]
Thanks very much cScotPlay! I appreciate the response and the fix.
