### ISSUE TITLE
Cant mine coal nether ore with Wood pickaxe and iron nether ore with gold pickaxe

### ISSUE THREAD

**Issue by GIThe13** [cScotPlay/BasicNetherOres#30]
When me and my friend are playing survival mod where we start in nether we use this mod. So we start to get Wood and gold. When we want to get iron we mine iron nether ore with golden pickaxe, but we don't get the item we literally disappointed cause in overworld we can mine iron ore with golden pickaxe, but with this mod we cant do that. Sorry my English is bad, because i'm Indonesian

**Comment by cScotPlay** [comment]
Sorry just now getting back to your issue. Yes all the ores were set to iron level pickaxe. This is feature that may be added in future versions. If we get it added I would like to have it configured so users can update it as they want.

**Comment by cScotPlay** [comment]
In the newest Forge version (1.17) this is updated
