### ISSUE TITLE
Compability with Amplified Nether

### ISSUE THREAD

**Issue by Andstar** [cScotPlay/BasicNetherOres#38]
There is a mod called Amplified Nether that makes the Nether 256 Blocks high. I wanted to spread the ores over the new full height but the highest point is at 125 so... can you make the max higher?

**Comment by cScotPlay** [comment]
Ah...good to know.  Yea I can adjust this in the next update.

**Comment by cScotPlay** [comment]
This is now updated with the Forge version 1.18.1-7.1.1.  Hope this helps.
