### ISSUE TITLE
Textures are incorrect

### ISSUE THREAD

**Issue by Watersfall** [cScotPlay/BasicNetherOres#39]
Expected Behavior: Textures are 16x16
Actual Behavior: They aren't

**Comment by cScotPlay** [comment]
Can you please provide a crashlog or more information to what is causing this conflict?  Thanks

**Comment by cScotPlay** [comment]
Textures are updated to read  the base resource packs netherrack fixing the issues with netherrack looking different than vanilla and supporting additional resource packs (Forge version 1.18.1-7.1.1)
