### ISSUE TITLE
Copper Ore too many OreDict entries

### ISSUE THREAD

**Issue by MeinKraft** [cScotPlay/BasicNetherOres#4]
Forge 28.0.104
BNO: 1.14.4-3.2.1

I think youve attached too many ore tags to the copper ore block
Heres a pic  https://1drv.ms/u/s!ArSGAcC04KWskl-qgEOadZABTR1j?e=A7oG0L

**Comment by cScotPlay** [comment]
Thanks for letting me know about this issue. Version 3.2.2 should fix this issue.
