### ISSUE TITLE
Textures are incorrect

### ISSUE THREAD

**Issue by Watersfall** [cScotPlay/BasicNetherOres#42]
Expected Behavior: You can visibly see 16x textures in the mod
Actual Behavior: Everyone but you sees higher than 16x textures

Attached screenshot https://cdn.discordapp.com/attachments/166630061217153024/937901915977687110/unknown.png

**Comment by cScotPlay** [comment]
The newest version has the ability to change the textures through the resource packs.  Please refer to version 7.1.2

**Comment by Watersfall** [comment]
Why are the only two options 32x garbage and obviously poorly downscaled translucent edged garbage?
