### ISSUE TITLE
[1.16.5][question] Osmium integration with other mods

### ISSUE THREAD

**Issue by bochen415** [cScotPlay/BasicNetherOres#43]
Should osmium ingots from this mod be accepted into a pulverizer (to make the dust version) from Thermal Series  mods with Mekanism in the pack?
They aren't in my pack, is there a config for that? I'm probably doing something wrong here.

Forge 36.2.21
thermal_expansion-1.16.5-1.4.2.4
thermal_foundation-1.16.5-1.4.3.10
cofh_core-1.16.5-1.4.2.9
Mekanism-1.16.5-10.1.1.456
and a bunch of other mods.

**Comment by cScotPlay** [comment]
Let me see what I can do.  It was set to work with most mods just not sure how they are looking at tags.
