### ISSUE TITLE
No config file?

### ISSUE THREAD

**Issue by ghost** [cScotPlay/BasicNetherOres#44]
There seems to be no way to configure the settings. By default Silver ore (for Occultism mod) is turned off. The UI specifies this can be changed in the config, but there is nothing available through the in-game mod menu config, nor the config folder in the instance directory. 
![NetherOreIssue](https://user-images.githubusercontent.com/101782179/158730842-f491e62e-c7f9-4080-bbbf-f45a83936f89.png)

**Comment by cScotPlay** [comment]
You have to open the config file through  window explorer or another text editor.

**Comment by luckycobble** [comment]
Where is the config file? I'm confused.

**Comment by Boomflex** [comment]
> Where is the config file? I'm confused.

You've probably figure it out as it was 2 weeks ago but the file is called "bno-common.toml" in the config folder of the instance.

**Comment by ghost** [comment]
There is no config file in the config folder for the installation...

**Comment by ghost** [comment]
I am also confused. There just wasn't a config file for this mod in the
config folder for the installation, nor was there any means of making the
adjustment through the in-game mod menu.
I tried a re-install of everything to no avail.
This was done through the curse forge mod manager/launcher if that helps at
all.
I've actually since given up on trying to fix it, myself, but I do
appreciate that you took the time to look into it!
