### ISSUE TITLE
Can't Mine any ores...

### ISSUE THREAD

**Issue by DragonBlood121** [cScotPlay/BasicNetherOres#47]
Hey this may be a stupid question and is not related to coding or a platform error but I can't seem to mine any of the ores even with a diamond pickaxe. I can't even mine coal, do I need a specific pickaxe or tool?

**Comment by cScotPlay** [comment]
If you are using the Forge version you will need to update to the 8.0.1 version for 1.19.  The 8.0.0 version had an error with the mining tags.
