### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MelanX** [cScotPlay/BasicNetherOres#5]
Could you add the license on GitHub? Because on CurseForge it’s MIT but maybe it’s another license for your source code. If there is no license it’s like All Rights Reserved as far as I know

**Comment by K0-RR** [comment]
Bump.
For now, it's MIT on the CurseForge, ARR on GitHub, and CC0-1.0 inside the fabric.mod.json file.

**Comment by cScotPlay** [comment]
License file was added to the newest branch and codified across the platforms and mod.
