### ISSUE TITLE
Unable to edit ore generation on server

### ISSUE THREAD

**Issue by TheLifeSpice** [cScotPlay/BasicNetherOres#50]
Game version: 1.19.2
Forge Version: 43.1.47
Basic Nether Ores Version: 1.19.2-8.2.0

Issue: Editing the bno-common.toml file doesn't change ore generation in the nether. Ore generation remains as default even though the client config file and the server file are changed from the original (client and server config are also consistent with one another).

Examples:

Changed section on config file: 
![image](https://user-images.githubusercontent.com/78243562/207697222-5ddfdd70-30ba-41a0-be9b-22a09c081280.png)

Screenshot from game where client and server are running edited config file: 
![2022-12-14_11 32 39](https://user-images.githubusercontent.com/78243562/207697528-2a6aa771-7b97-4c49-a0d8-88b1f6088172.jpg)

Another Example: 
![Capture2](https://user-images.githubusercontent.com/78243562/207698386-c01aac26-a40f-42d2-a064-4a4a1fe28b85.PNG)
![Capture](https://user-images.githubusercontent.com/78243562/207698086-4801c49a-e6e5-457e-8c20-b5767d98162a.PNG)

(Let me know if I'm being dumb or editing the config file/the wrong file incorrectly)

**Comment by cScotPlay** [comment]
yes, this is an issue with the newest version of Nether Ores.  The config file is basically useless and is set to come out in the next update.  To update ore placement and the ores that generate in the world, you need to manipulate the data pack.  Once loaded into the world, it will update and have the setting you are looking for.

**Comment by TheLifeSpice** [comment]
Thank you so much for the work around. I'll try to manipulate the datapack on my own and see if that works.

No rush on your end (I appreciate the work that you do already) but do you have any rough idea when the config file will be operational for Basic Nether Ores and Basic End ores?
