### ISSUE TITLE
Performance issues [1.19.2]

### ISSUE THREAD

**Issue by itsdinkd** [cScotPlay/BasicNetherOres#52]
![image](https://user-images.githubusercontent.com/35115304/210672128-a2725e11-53bc-4a47-8bc8-0c7184b7f4a5.png)
https://spark.lucko.me/ez1Pyl05hS

I believe bno is somehow affecting mobcaps as well. 
![image](https://user-images.githubusercontent.com/35115304/210672170-aab09a66-b375-457b-bced-7cdc8a24cee4.png)

the above screenshot is after I killed skeletons, which had 1100 spawned.
![image](https://user-images.githubusercontent.com/35115304/210672195-c99b27dc-7509-47f8-91fb-2d7f0a282ad2.png)

**Comment by cScotPlay** [comment]
Sorry but I fail to see how this is a Basic Nether Ores issue.

**Comment by itsdinkd** [comment]
By all means im not a java developer so I trust your word however going off the spark report it shows that BNO is spending a lot of time catching exceptions. turns out the mobcap thing was something else however the main issue is still present that when I had BNO running in our modpacks server BNO was showed as vvv
![image](https://user-images.githubusercontent.com/35115304/212503405-c5d139f8-998c-47ab-a25b-282ac6970346.png)

**Comment by cScotPlay** [comment]
Ok that I think I can look at and work with.  What version are you using? Also what other mods are you using this with?  Do you have a modpack on CurseForge I can pull down to review?

**Comment by EvionFox** [comment]
Hi! I'm having the same issue looking at my spark health reports. If it helps, I'm running Fabric 1.19.2, with the latest release of BNO
My modpack can be found here: https://www.curseforge.com/minecraft/modpacks/lynxsmp

**Comment by cScotPlay** [comment]
I've been unable to reproduce this.  I'll keep an eye on it through future development.  Thanks.
