### ISSUE TITLE
1.19.2 Fabric Nether Ores are not minable + 1 more issue

### ISSUE THREAD

**Issue by Adome11** [cScotPlay/BasicNetherOres#57]
![image](https://github.com/cScotPlay/BasicNetherOres/assets/143525804/10c65300-c82a-4c46-a46a-2e75074896ea)

Coal has no x16 texture, and EVERY single ore is unharvestable. Iron pickaxes, Netherite pickaxes, it doesn't matter it's completely broken.

No other mods installed.

**Comment by cScotPlay** [comment]
Thanks for letting me know about these issues.  Fixed in version 8.2.2.  Also please remember to erase the x16 Resource Pack in the resource pack folder to allow the new one to build and update the texture.
