### ISSUE TITLE
Can you make the "Aluminum" compatible with IC2 classic "Aluminium" (with +1 i)

### ISSUE THREAD

**Issue by OHOgameplay** [cScotPlay/BasicNetherOres#58]
Currently due to the name mismatch, they are not compatible.

**Comment by cScotPlay** [comment]
I can sure look into it in the future update.  What version and loader are you using?

**Comment by OHOgameplay** [comment]
Forge, and Minecraft 1.19.2

**Comment by OHOgameplay** [comment]
A bit of additional info:
For example the Nether (and End) emerald, diamond, redstone, lapis, coal, silver, iron, tin, and uranium ore are compatible.
The only thing that is not compatible, but is present in both mods is the "Alumin(i)um".

An example of the nether copper ore working with IC2 classic machine:
![2023-09-22_15 09 55](https://github.com/cScotPlay/BasicNetherOres/assets/124529188/1578c77a-76d6-4e96-ba42-3e110f434a9a)

**Comment by cScotPlay** [comment]
Been updated for 1.21.  Will work on support for 1.20.1.
