### ISSUE TITLE
[1.20.1] [Forge 47.2.17] Mekanism ores are not being generated

### ISSUE THREAD

**Issue by Insomniac-Ossifrage** [cScotPlay/BasicNetherOres#59]
Hello,

I have recently updated the mod to version: 'forge-1.20.1-9.1.1' and noticed that Mekanism ores are not spawning in the nether (e.g. Uranium, Osmium, etc.). These appear to spawn in Minecraft version 1.19. However, I am unsure if it's supported in the new version.  

Thank you in advance. 

### Details

> Minecraft: 1.20.1
> Forge: 47.2.17
> Mekanism: 1.20.1-10.4.5.19

BNO Filtered Client Logs: 
```shell
Reference map 'bno.refmap.json' for bno.mixins.json could not be read. If this is a development environment you can ignore this message
Reference map 'bno.refmap.json' for bno.forge.mixins.json could not be read. If this is a development environment you can ignore this message
```

**Comment by cScotPlay** [comment]
Thanks for reporting this.  Let me see what I can do to fix this.

**Comment by halvors** [comment]
I am experiencing this very same issue, before it was possible to enable this in config, but that is not available in the 1.20.1 version.

**Comment by halvors** [comment]
Any progress on this?

**Comment by cScotPlay** [comment]
Okay I've looked into this and both ores are spawning in the multiple test worlds.  Just a thought, but are you using the datapacks that has all the ores?  The basic datapack only accounts for the vanilla ores?  You can pull the datapacks from version 9.1.0.

**Comment by Insomniac-Ossifrage** [comment]
Thank you for your reply, Scot. Unfortunately, I may need some of your help troubleshooting the datapacks.

During world-gen the BNO datapack is enabled; however, only one option is available. As such, I don't know how to distinguish between the two different datapack variants that you are describing.

I've tried BNO versions 9.1.1 and 9.1.0. All downloaded from CurseForge.

Thanks again

**Comment by halvors** [comment]
> Okay I've looked into this and both ores are spawning in the multiple test worlds. Just a thought, but are you using the datapacks that has all the ores? The basic datapack only accounts for the vanilla ores? You can pull the datapacks from version 9.1.0.

How can i obtain these datapacks? They are not linked anywhere on the curseforge site?...

**Comment by halvors** [comment]
Found it, that solved it for me. Though very hard to find, and literally no documentation on where to locate these files, maybe these could be added to the Readme file and the page on CurseForge? Just a suggestion :-)

**Comment by Insomniac-Ossifrage** [comment]
@halvors Could you please elaborate on where you found the datapacks? Thanks

**Comment by Insomniac-Ossifrage** [comment]
Found it as well. For anyone interested here are the steps to follow for CurseForge:

1. Go to the modpage on CurseForge and select the '[Files](https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores/files)' tab.
2. Filter for Minecraft version 1.20.1.
3. Find BNO mod version 9.0.1. The text reads as 'Basic Nether Ores-1.20.1-9.1.0 - Forge'. Inmediately to the right of the name, a +2 should appear, which indicates that two more files are present.
4. Click on the name. You should land [here](https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores/files/4703720).
5. Scroll to the 'Additional Files' section. There you should find two datapacks.
