### ISSUE TITLE
[1.21] Basic End Ores end Nether Ores issue with latest forge

### ISSUE THREAD

**Issue by Periam** [cScotPlay/BasicNetherOres#61]
Installed the latest version of the mods for MC 1.21 and Forge and it crashed

MC 1.21
Forge 51.0.17
bno-forge-1.21-10.0.0.jar
BasicEndOres-forge-1.21-5.0.0.jar

![image](https://github.com/cScotPlay/BasicNetherOres/assets/13920185/ae57fa71-4866-4416-80a8-d279c061e972)

Crash logs
[crash-2024-06-24_14.46.33-fml.txt](https://github.com/user-attachments/files/15959498/crash-2024-06-24_14.46.33-fml.txt)

**Comment by cScotPlay** [comment]
Version 10.0.1 solves this issue.
