### ISSUE TITLE
Ores are not dropping anything 1.21

### ISSUE THREAD

**Issue by Jayv6** [cScotPlay/BasicNetherOres#64]
When i am mining the ores in the nether they drop nothing.
it is the same with the end ores as well.
also i tried to vein mine the ore and it crashed one me
https://mclo.gs/ZGeyuTM (log)

**Comment by cScotPlay** [comment]
Fixed in version 10.0.2 for Nether Ores and 5.0.2 for End Ores.  Thanks for highlighting this issue.
