### ISSUE TITLE
MC 1.20.1 [Fabric] No method for configuring ore spawn values.

### ISSUE THREAD

**Issue by Steven-OConnell** [cScotPlay/BasicNetherOres#65]
There is no longer a way to adjust ore spawn values _(via config or otherwise)_ unlike previous versions, you say there is a datapack available for customization but is that only the Forge version?
I'm at a loss as to how I can adjust the spawn values for various ores.

Mod Loader - Fabric
Minecraft version - 1.20.1
Mod version - 9.1.1

_(I should also note that this is a problem with Basic End Ores as well)_

**Comment by cScotPlay** [comment]
This is correct.  You can update the values via the data packs.  Pull them from the forge version and you can adjust as you would like.  Due to the newest way that Minecraft generates the ore features they are all built via data packs and only adjustable in the json files.

**Comment by Steven-OConnell** [comment]
Alright, thanks.
Providing a link to the datapack on the mod page (For both End & Nether) would be beneficial for Fabric users, that way they don't have to set up a separate forge client just to grab a copy of the datapacks.
