### ISSUE TITLE
Ore Tooltip always says "World Generation Disabled"

### ISSUE THREAD

**Issue by rckymtnrfc** [cScotPlay/BasicNetherOres#7]
FYI, the tooltip when hovering over ores that are enabled (and confirmed to be spawning) shows "World Generation Disabled - Enable through Config File"

This doesn't happen on the vanillas ores, just mod ones (copper, tin, silver, etc).

Forge - 31.1.30
BNO - 1.15.2-4.0.0

Thanks

**Comment by TheUntamed** [comment]
Have you enabled the generation of these ores? If I do so the message disappears like expected.

**Comment by rckymtnrfc** [comment]
Yes, I have then enabled and I confirmed they are generating in the nether, yet I'm still seeing that tooltip.

**Comment by TheUntamed** [comment]
weird. For me it's the other way around.
Tooltip is gone, ores still not generating

**Comment by cScotPlay** [comment]
Interesting.  Let me take a look and see what I can find out.

**Comment by cScotPlay** [comment]
Okay looked at it and can reproduce this.  Not sure yet what exactly is happening but it appears.  It seems that for some reason the tooltips do not want to update from the initial loading.  I'll look further into it but it may be just easier for now to remove this functionality.

**Comment by rckymtnrfc** [comment]
As a work around, I just made a resource pack with the en_us.json being replaced with one that has that text blanked out.  Thanks for looking into it.

**Comment by cScotPlay** [comment]
Thank you for bringing this to my attention.  Think we got it worked out.  Version 4.0.1 was just uploaded and should take care of the issue you were having.

**Comment by rckymtnrfc** [comment]
Thanks for the quick fix!
