### ISSUE TITLE
More Ores

### ISSUE THREAD

**Issue by TheUntamed** [cScotPlay/BasicNetherOres#8]
Are you planning to add more ores?
If yes here are some suggestions:
Zinc (e.g. Silents Mechanisms or Blue Power)
Magmite (e.g. Omega Craft)
Platinum (e.g. Silents Mechanisms)
Osmium (e.g. Mekanism)
Tungsten (e.g. Blue Power)
Ruby, Sapphire, Amethyst, Malachite (e.g. Blue Power)
Biotite (e.g. Quark)
Prosperity (e.g. Mystical Agriculture)
Inferium (or maybe even a higher Essence level?) (e.g. Mystical Agriculture)
Xp Ore (no example)
Steel (I mean it's the nether)

**Comment by cScotPlay** [comment]
This is a tough one and I'm currently undecided on it.  A lot of people as for additional ores and we've added some of them.  At the same time, it is supposed to be pretty basic and the more that is added sorts of takes away from that.  Yea it is tough but I'll be the first to tell you all if we are going to add more.
