### ISSUE TITLE
[1.15.2] Modded Ores not generating

### ISSUE THREAD

**Issue by TheUntamed** [cScotPlay/BasicNetherOres#9]
I enabled the modded ores (Copper, Silver, Lead, Tin, Aluminium, Uranium) in the config and the tool tip message "World Generation Disabled" is replaced with coordinates, but the ores are still not generating.

And it wasn't just bad luck. I searched quiet well:
![Screenshot_2](https://user-images.githubusercontent.com/48363903/78694521-1275f200-78fd-11ea-9b00-7fdbf68f0370.jpg)

The Vanilla Ores are generating.

**Comment by cScotPlay** [comment]
A couple of questions to try and narrow this down.  First, are you testing this in a single player world?  If so, did you enable the ores after you initially loaded into the world?

**Comment by TheUntamed** [comment]
I found out what causes this problem.
You are generating 2 config files. 1 in the "confi" folder and one in the "defaultconfig"/"serverconfig" folder. Both configs are the same and contain booleans to disable ore generation.
If you enable the generation in the "defaultconfig"/"serverconfig" folder the red message goes away but the ores are not generating.
If you enable the generation in the "config" folder, the ores generate but the message is still there.
You should just create 1 of the configs.

**Comment by cScotPlay** [comment]
Thank you for bringing this to my attention.  Think we got it worked out.  Version 4.0.1 was just uploaded and should take care of the issue you were having.  I have only one config now.  Something weird was creating them both.  It should be worked out and functioning properly.
